version: "3.9"
services:
  db:
    image: lscr.io/linuxserver/mariadb
    restart: always
    volumes:
      - "C:\\Docker\\MariaDB:/config"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:alpine
    restart: always

  panel:
    build: .
    environment:
      DBHOST: "db"
      REDISHOST: "redis"
    volumes:
      - "C:\\Docker\\Panel:/config"
    depends_on:
      - db
      - adminer
      - redis
    #command: "php8 /var/www/pterodactyl/artisan queue:work --queue=high,standard,low --sleep=3 --tries=3"
